name: Run all tests

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * SAT'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: workflow/nix-shell-action@v3.3.0
        with:
          flakes-from-devshell: true
          script: zig build test
