name: Run all tests

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * SAT'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: workflow/nix-shell-action@v3
        with:
          packages: zig
          script: |
            zig build test
